[project]
name = "agentica-mini-nixos"
version = "0.1.0"
description = "Using agentica to control a full Linux NixOS VM"
dependencies = ["agentica"]

[dependency-groups]
dev = ["pyright>=1.1.403"]

[tool.uv.sources]
agentica = { path = "./agentica-mini", editable = true }
